### ISSUE TITLE
Is the code and model link still available?

### ISSUE THREAD

**Issue by IceFlameWorm** [Jianlong-Fu/Recurrent-Attention-CNN#11]
I tried to get the model source code from the link in the README, but the link was not accessible. If someone has gotten the source code, would you mind give me a backup?

**Comment by ForrestGan** [comment]
+1

**Comment by yyfwlllid** [comment]
+1

**Comment by y-dep** [comment]
+1s

**Comment by JingyunLiang** [comment]
See [https://github.com/Jianlong-Fu/Recurrent-Attention-CNN/issues/3](https://github.com/Jianlong-Fu/Recurrent-Attention-CNN/issues/3) （BaiduYun is available)

**Comment by IceFlameWorm** [comment]
@MichaelLiang12  Thank you, I will try BaiduYun later.

**Comment by IceFlameWorm** [comment]
https://pan.baidu.com/s/1pL6vS63, this is the link of baiduyun shared by KawhiWang in [#3](https://github.com/Jianlong-Fu/Recurrent-Attention-CNN/issues/3)
