### ISSUE TITLE
AttentionCrop Layer: Where can we find it?

### ISSUE THREAD

**Issue by ParitoshParmar** [Jianlong-Fu/Recurrent-Attention-CNN#5]
Hi Jianlong,

You have used AttentionCrop layer, but, I think, you have not released it. Can you please make it available?

Thank you

**Comment by Geeshang** [comment]
Same here, this Caffe code can not run without the "AttentionCrop", which I think to be one of the core layers of the paper, where is it?

**Comment by Geeshang** [comment]
The new download link includes the "AttentionCrop" layer. 
https://1drv.ms/u/s!Ak3_TuLyhThpkxifVPt-w8e-axc5

**Comment by tracycw** [comment]
how about the rank-loss layer???

**Comment by ParitoshParmar** [comment]
@tracycw I think they have provided the code for verification purpose, that's why it doesn't contain ranking loss layer. But here is a good starting point for ranking loss layer: https://github.com/wanji/caffe-sl
